### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by andros21** [andros21/rustracer#24]
## todo 📘 

- [x]  @Paolo-Azzini  | try to improve unit test coverage removing useless traits from`#derive` macro of each class
- [x]  @Paolo-Azzini  | try to improve unit test coverage using `new` instead direct object initialization
- [x] @Paolo-Azzini   | uniform return type for traits and methods, when `Self` is correct to be used?
- [x] @andros21  | but if `UnableToNormalize` is used only inside tests, we can delete it
- [x] @Paolo-Azzini   | a simple test for `onoffrender.solve` is possible? And for `ray_intersaction` in `world`?
- [ ] ~~@Paolo-Azzini | A impl `::from` tuple for `Vector2D` in `misc.rs` could be useful to lighten syntax, no?~~\
      And little unit test for `Vector2D::isclose`
      >> Actually i think `Vector2D::from((f32, f32))` is heavier syntax than `Vector2D{u: f32, v: f32,}`
- [x] @Paolo-Azzini   | flat renderer + antialising
- [x] @Paolo-Azzini   | improve in `cli` (complete+manpage) using [clap](https://docs.rs/clap/latest/clap/index.html#related-projects) related projects
- [x] @andros21        | add `rustfmt.toml` ([alacritty](https://github.com/alacritty/alacritty) for some ideas 💡)
       >>  😢 ly the major cool things aren't in stable `rustfmt` ... we'll see
- [x] @andros21        | try to remove duplication in `main` function in inside `main.rs`
- [x] @andros21        | check support file format ldr image before convert or render the image!
- [ ] ~~@andros21   | best rust workflow to emulate python setup/tear_down in unit tests, useful e.g. `imagetracer.rs`~~\
       >> 👀 at it ... it's nightmare, no advantages in my opinion 
- [x]  @andros21       | fire up CD pipeline, `ci-cd` branch already open, `cd.yml` missing
- [ ] ~~@andros21       | profiling `flamegraph` `heap_allocator`? dev dependencies?~~\
       >> too much work and study for a dummy dev, performance and benchmark are projects alone
- [x]  @andros21       | reformat `error.rs` so that source error are printed at new line
- [ ] @andros21        | when macro [`#[no_coverage]`](https://github.com/rust-lang/rust/issues/84605) will be stable, bypass coverage test for `main.rs`, `cli.rs`, etc ...
- [x]  @andros21 | after the bottleneck is found try to improve performance using multi-threading ([rayon](https://docs.rs/rayon/latest/rayon/))

other improvements're welcome!
